spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hLoad?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Moscow
    platform: mysql
    username: hLoadApp
    password: q1